### ISSUE TITLE
ENTRYPOINT is too time consuming.

### ISSUE THREAD

**Issue by danielpclark** [jfloff/docker-heroku-rails#1]
The init script runs every single time a Heroku instance spins up for containers including this because you used `ENTRYPOINT`.  If the `bundle install` command takes more than 60 seconds the request fails.  Also this is time added to delaying a website response.

In my fork I just put a message in it at the end:

```
RUN echo "Be sure to 'RUN init.sh' in the container using this one."
```

**Comment by jfloff** [comment]
Well the init is supposed to only be run once at container startup. It does have some time consuming operations namely:
- Checking and installing missing gems
- Performing pending migrations
- (if Production) Precompile assets
- And running other post-startup scripts

But since its a one-time job I didn't saw too much harm in it. I'm sure it won't affect website response after its first run.

Could you tell me how do you use this image? So far I have only used for my own project in a mainly dev environment. Are you using this in a production-like env? If so, maybe it's better if I add some conditions to not perform some tasks (e.g. install gems) when the env is Production. What do you think?

Cheers!

**Comment by danielpclark** [comment]
I suppose you may be using this as a **buildpack** and not for a **container**.

I used `heroku stack:set container` and [Heroku's new build manifest](https://devcenter.heroku.com/articles/heroku-yml-build-manifest) to point to [my version of this Docker image](https://github.com/danielpclark/heroku-rails-vuejs) and ran into trouble because any Docker container using another Docker container with an **ENTRYPOINT** will run the **ENTRYPOINT** command everytime it runs its own **ENTRYPOINT** or **CMD**.  Since my container is also installing and precompiling JavaScript assets with `yarn` the job would time out because Heroku's 60 second limit is reached before the web request can respond.

So my issue I opened up here is likely because I'm not using it as you are: buildpack vs container.

As for writing it to check for **production** I'd advise against those changes.  I think it should be production either way with buildpack or container.

**Comment by jfloff** [comment]
I do use it as a container, but I use it only for development. So the last comment you made doesn't make much sense to me since I use it for dev. But I do have to set **RAILS_ENV** and **RACK_ENV** to ``development``. For example, [I only precompile assets when in development](https://github.com/jfloff/docker-heroku-rails/blob/master/init.sh#L20).

I did not know this **ENTRYPOINT** thing with the build manifest, but we could easily set this as a **CMD** and have the same effect no? WDYT?

**Comment by danielpclark** [comment]
I don't know I haven't tried it, but I think **CMD** would prevent this problem.

How would you set **RACK_ENV** and **RAILS_ENV** when you don't have them in your Dockerfile?  The precompile check is useless without the option to set it.  From my experimentation if the environment isn't manually written in the Dockerfile, or provided via an env file, then the only place to add the environment variables in is on the **CMD**/**ENTRYPOINT** line.  My point being the `if [ "$RAILS_ENV" == "production" ]` line is pointless since it's never set in the Dockerfile.

Since you're not using this as a buildpack this issue still exists.

But what matters I guess is whether you planned on this being used publicly as a buildpack (which is what I thought you got this from), or as a container, or just your own personal project not meant to be depended upon.

**Comment by jfloff** [comment]
This is definetly an attempt at a container that you can use for both development and production. Thing is, I don't use it for production, only on a development environment. That is why I was asking for your feedback.

Regarding **RACK_ENV** and **RAILS_ENV** [I set them up when I run with ``--env`` ](https://docs.docker.com/engine/reference/builder/#env), or using docker-compose. 

Finally, the ``init.sh`` script was driven from my experience during development. The fact even if I forget to install gems or migrations, on startup it will set them up, I found it useful. But I don't want to force people down that path either, I want their feedback on the ``init.sh`` script.

**Comment by danielpclark** [comment]
Okay.  What you need to know about Heroku is that you're not able to specify how the command line starts docker.  So you don't have access to `--env`.  Because of this for the script to work on their server you “may” need some defaults.

```
ENV RACK_ENV=production \
    RAILS_ENV=production \
    LANG=en_US.UTF-8 \
    RAILS_LOG_TO_STDOUT=true \
    RAILS_SERVE_STATIC_FILES=true \
    DATABASE_URL=postgresql:does_not_exist
```

The precompile need both the `RAILS_ENV` and `DATABASE_URL` set to something to work.  Then when you have Heroku run the container the one of two ways to get the `DATABASE_URL` into the container is for users to either put it in their own **CMD** line like:

```
CMD DATABASE_URL=$DATABASE_URL puma -C config/puma.rb -p $PORT
```

_Heroku requires `$PORT` to be set at run time.  This is not your concern for this Dockerfile, only for those who use it._

The other way to set environment variables I found by emailing Heroku.

## My Email to Heroku

```
Hey Heroku team!

I've successfully built a Docker image on Heroku and it works well for
my purposes.  But I'd like to make my work available and useful to
others.  For that I need to allow some of the ENV vars into a container
for the ONBUILD command.  I have found that that should be possible:

    ONBUILD ARG REPO_PATH
    ONBUILD ENV REPO $REPO_PATH
    ONBUILD ADD . /app/$REPO

    And build child image with build-arg option (docker build
--build-arg REPO_PATH="xxx").

Could you update the Heroku Build Manifest from

build:
  docker:
    web: Dockerfile
    worker: worker/Dockerfile

To something with build_args?

build:
  docker:
    web: Dockerfile
      build_args:
        - REPO_PATH=/app
        - RUBY_VERSION=2.4.3
        - DATABASE_URL=$DATABASE_URL
    worker: worker/Dockerfile

And that will allow each of those to be passed in as `--build-arg
REPO_PATH=/app --build-arg RUBY_VERSION=2.4.3 --build-arg
DATABASE_URL=$DATABASE_URL`.

This would allow me to change my Dockerfile so it can be used by others
in the FROM field and make a customizable Rails/Webpacker/VueJS
container as simple as a one or two liner Dockerfile.

Thanks!
  -Daniel
```

## Heroku Replies

```
Daniel,

Thank you for the feedback.
This is actually something you can already do, though not per process.


    build:
      docker:
        web: Dockerfile
        worker: worker/Dockerfile
      config:
        REPO_PATH=/app


When using our languages support, we will add that config to the generated
Dockerfile. When using your own dockerfiles, we will pass the value as
`--build-arg`.

Please let us know how using this goes.

Cheers,
Damien
```

Using this information you could either put the defaults in the `Dockerfile` as I have done, or give instruction in your `README` for how all your users can update their `heroku.yml` file and `Dockerfile` to use the config/onbuild/arg/env to set each Heroku ENV they want.

This should be documented since Heroku doesn't have this information publicly available.

**Comment by jfloff** [comment]
Is this related to the new [heroku.yml approach](https://devcenter.heroku.com/articles/heroku-yml-build-manifest)? I wasn't aware of this new approach, I'm still going through it but it looks very interesting. It would be amazing if we could set this repo as a "standard" for rails apps on Heroku! Sidenote: If you feel like it, we could both build this from this point onwards (I could add you as contributor).

Back to your feedback, this solution using the `config` on `heroku.yml` looks good.

Let's do this. When I have time I will try to migrate my own heroku projects to the new `heroku.yml` approach. When I do this, I'll change this repo, and I will get back to you for more feedback. Meanwhile feel free to suggest something, or even submit a PR!

**Comment by danielpclark** [comment]
> Is this related to the new heroku.yml approach?

Yes

I went ahead and made 3 of my own containers forked from this.

* master = heroku/heroku:16 — for just running your site with Heroku's base image
* build = heroku/heroku:16-build — for compiling your site with Heroku's base image
* baseimage = phantom/baseimage — true Linux system behavior with pid server to avoid orphaned processes (also smaller than Heroku's container).  Should run better overall.

They're automatically built on Docker Hub each time they're updated so people can pull prebuilt images.

You can check them out if you'd like.  It uses the latest nodejs, yarn, and Ruby 2.5.0. https://github.com/danielpclark/heroku-rails-vuejs/ .  The baseimage branch is the recommended one.

Serious websites won't use my docker images as they are since I don't have nodejs or yarn locked in at a specific version… yet.  Also on the TODO list is to print out versions for all installed items during the startup sequence for logging purposes.

If you wouldn't mind I'd suggest looking at these to get an idea for improvements.  I may come and contribute more to this repository itself but for now I'm content with what I've managed to build.

You can try out what your site would run like in production on your own machine with these images as it's defaulted that way.  You only need to specify the `DATABASE_URL` and `PORT` when you start it, details should be in the `README`.  I like to use the actual database from Heroku production environment which the `heroku config` command will be nice enough to give you.
