### ISSUE TITLE
Heroku 22?

### ISSUE THREAD

**Issue by conroywhitney** [jfloff/docker-heroku-rails#6]
Hey @jfloff -- is there a reason why you backpeddled on the `heroku-22` image?

https://github.com/Rnters/docker-heroku-rails/commit/507ebacc1a87c14fa853db80236de1bcdd4efc8f

Was there some issue with Rails compatibility?

**Comment by jfloff** [comment]
Indeed there was a problem with heroku download links. I will be looking at it again today.

**Comment by jfloff** [comment]
Looks like it is working now. Closing
